# Generated by Django 4.1.7 on 2023-03-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.IntegerField()),
                ('address', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('blood', models.CharField(max_length=10)),
                ('volume', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'donor_detail',
            },
        ),
    ]
