# Generated by Django 4.1.7 on 2023-03-11 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('blood', models.CharField(max_length=10)),
                ('volume', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'donor_detail',
            },
        ),
        migrations.CreateModel(
            name='Patient_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=200)),
                ('patientAge', models.IntegerField()),
                ('patientGender', models.CharField(max_length=10)),
                ('patientContact', models.CharField(max_length=15)),
                ('patientBlood', models.CharField(max_length=10)),
                ('patientBloodVolume', models.FloatField()),
                ('patientPhysician', models.CharField(max_length=200)),
                ('patientStatus', models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Handed-Over'), ('4', 'Denied')], max_length=50)),
                ('patientRequestDate', models.DateField(default=django.utils.timezone.now)),
                ('patientRequisitionDate', models.DateField()),
            ],
            options={
                'db_table': 'patient_detail',
            },
        ),
    ]
