# Generated by Django 4.1.7 on 2023-03-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donar_Detail',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.IntegerField()),
                ('address', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('blood', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('volume', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'Donar_Detail',
            },
        ),
    ]
