# Generated by Django 4.1.7 on 2023-03-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_detail',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False),
        ),
    ]
