# Generated by Django 4.1.7 on 2023-03-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_detail',
            name='patientAge',
            field=models.CharField(max_length=3),
        ),
    ]
