# Generated by Django 4.1.7 on 2023-03-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS_App', '0003_alter_donor_detail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_detail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
