# Generated by Django 4.1.7 on 2023-03-12 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS_App', '0005_alter_patient_detail_patientrequestdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_detail',
            name='patientRequestDate',
            field=models.DateField(default=datetime.datetime(2023, 3, 12, 4, 9, 56, 126487, tzinfo=datetime.timezone.utc)),
        ),
    ]
